### PR TITLE
add softwares

### PR DESCRIPTION
**Pull request by jrezzende**

### CODE REVIEW

**Comment by espindolaa** [comment]
I don't think we should put DuckDuckGo under Web Browser

**Comment by jrezzende** [comment]
Agreed.
Changed it to Search Engine.

**Comment by espindolaa** [comment]
I've looked into it, it seems DuckDuckGo isn't actually open source. Do you have a link to the source code?

**Comment by jrezzende** [comment]
looked further into and it seems that they plan on being open source eventually.
removed duckduckgo as it is not an open source software

**Pull request merged**
